services:
  mariadb:
    container_name: "mariadb"
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    restart: on-failure
    networks:
      - wordpress-mariadb
    volumes:
      - mariadb-volume:/var/lib/mysql
    env_file:
      - .env
    environment:
      TZ: Asia/Seoul

networks:
  wordpress-mariadb:

volumes:
  mariadb-volume:
