services:
  mariadb:
    container_name: "mariadb"
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    command: --init-file /data/application/init.sql
    restart: on-failure
    networks:
      - wordpress-mariadb
    volumes:
      - mariadb-volume:/var/lib/mysql
      - ./requirements/mariadb/conf/init.sql:/data/application/init.sql
      - ./requirements/mariadb/conf:/etc/mysql/conf.d
    env_file:
      - .env
    environment:
      TZ: Asia/Seoul

  wordpress:
    container_name: "wordpress"
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - mariadb
    networks:
      - nginx-wordpress
      - wordpress-mariadb
    volumes:
      - wordpress-volume:/var/www/html/wp-content
    env_file:
      - .env

  nginx:
    container_name: "nginx"
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    depends_on:
      - mariadb
      - wordpress
    ports:
      - 443:443
    restart: on-failure
    networks:
      - nginx-wordpress
    volumes:
      - wordpress-volume:/var/www/html/wp-content
    env_file:
      - .env
      
networks:
  nginx-wordpress:
  wordpress-mariadb:

volumes:
  mariadb-volume:
  wordpress-volume:
