services:
  mariadb:
    container_name: "mariadb"
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    restart: on-failure
    networks:
      - wordpress-mariadb
    volumes:
      - mariadb-volume:/var/lib/mysql
    env_file:
      - .env

  wordpress:
    container_name: "wordpress"
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - mariadb
    networks:
      - nginx-wordpress
      - wordpress-mariadb
    volumes:
      - wordpress-volume:/var/www/html/wp-content
    env_file:
      - .env

  nginx:
    container_name: "nginx"
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    depends_on:
      - mariadb
      - wordpress
    ports:
      - 443:443
      - 80:80 # subject does not required http but I will redirect http to https
    restart: on-failure
    networks:
      - nginx-wordpress
    volumes:
      - wordpress-volume:/var/www/html/wp-content
    env_file:
      - .env
      
networks:
  nginx-wordpress:
    driver: bridge
    name: nginx-wordpress
  wordpress-mariadb:
    driver: bridge
    name: wordpress-wordpress

volumes:
  mariadb-volume:
  wordpress-volume:
